export const framework = [
  {
    content: '支持最新的Vue3.X版本🎆 配套新版Vue Router 4.X Proxy、Setup、Hooks等特性超前体验加强对TS的支持，快来开箱使用吧。🤣',
    avatar: 'https://vuejs.org/logo.svg',
    title: 'Vue3',
    github: 'https://github.com/vuejs/vue',
    color: '#7E4F66',
    author: '渐进式JS框架',
  },
  {
    content: '号称新一代前端开发与构建工具🎆，极速启动、原生ESM、HMR热重载、TS支持、Rollup插件等等<br>2022超火生态还等什么？💕',
    avatar: 'https://vitejs.cn/logo.svg',
    title: 'Vite',
    github: 'https://github.com/vitejs/vite',
    color: 'bg-orange-400',
    author: '新一代构建工具',
  },
  {
    content: '2021全球语言持续霸榜，始于JavaScript，归于JavaScript🎆，构建大型应用程序、先进的JS语法支持、大厂前端必备基础。🛵',
    avatar: 'https://raw.githubusercontent.com/remojansen/logo.ts/master/ts.png',
    title: 'TypeScript',
    github: 'https://github.com/Microsoft/TypeScript',
    color: 'bg-cyan',
    author: 'JS的超集',
  },
  {
    content: '只有1kb经典之作支持、Vue devtools 挂钩🎆、类型安全、模块化设计、关联本地存储的响应等等更多新特性🍡<br>学不动？Come on 卷起来',
    avatar: 'https://pinia.vuejs.org/logo.svg',
    title: 'Pinia',
    github: 'https://github.com/vuejs/pinia',
    color: 'bg-yellow-400',
    author: 'Vuex最佳替代品',
  },
  {
    content: 'UnoCss是一个功能类优先的CSS框架，它集成了原子式的css类名，它们能直接在脚本标记语言中组合起来，构建出任何设计。😛',
    avatar: 'https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg',
    title: 'UnoCss',
    github: 'https://github.com/unocss/unocss',
    color: '#22D3EE',
    author: '原子式CSS',
  },
  {
    content: '饿了么大前端团队出品，使用 TypeScript 开发，提供完整的类型定义文件，使用Vue3.0Composition API 降低耦合，新特性重构挂载类组件',
    avatar: 'https://element-plus.gitee.io/images/element-plus-logo.svg',
    title: 'Element Plus',
    github: 'https://github.com/element-plus/element-plus',
    color: 'bg-blue-600',
    author: '大厂出品',
  },
  {
    content: 'Vue Use是一组基于Composition API的实用函数，是目前世界上Star最高的同类型库之一<br>非常方便，谁用谁知道',
    avatar: 'https://vueuse.org/logo-vertical.png',
    title: 'Vue Use',
    github: 'https://github.com/vueuse/vueuse',
    color: 'bg-green-600',
    author: 'Vue工具集',
  },
];
